### ISSUE TITLE
ValLinkagePartialKey(generateEncoder) missing

### ISSUE THREAD

**Issue by forki** [thoth-org/Thoth.Json#110]
`FSC : error FS0193: Das Modul bzw. der Namespace "Encode" aus der Kompilierungseinheit "Thoth.Json" enthielt nicht den Wert "ValLinkagePartialKey(generateEncoder)". [/home/gitlab-runner/builds/yojQYPy-/0/a-team/eCarApp/src/Dashboard/Dashboard.fsproj]
`

After paket update I'm getting this weird compiler error. It's complaining that Thoth.Json is missing ValLinkagePartialKey(generateEncoder) - whatever that means.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/124718864-d6b64780-df06-11eb-8a6f-bc9092426172.png)

**Comment by MangelMaxime** [comment]
Similar to #46 

Yesterday, I released a new version of Thoth.Json which change the exposed API even if that was just optional arguments being deleted.

I released Thoth.Fetch to avoid the issue linked in theory, but it seems like Thoth.Fetch require FSharp.Core 5.0.0. I just release a new version of Thoth.Fetch to lower to FSharp.Core 4.7.2 can you please give it a try?

I also released a new version of Elmish.Debugger.

So, in theory I re-published all the package I have control over with the new version of Thoth.Json. I hope this will fix the problem.

**Comment by forki** [comment]
thanks that seems to work!
