### ISSUE TITLE
Suggestion: Expose isomorphic functions for parsing a JsonValue from a string

### ISSUE THREAD

**Issue by njlr** [thoth-org/Thoth.Json#112]
Sometimes, a service should expect valid JSON but does not care about the JSON schema. In these cases, we need to work with `JsonValue` but not strongly-typed decoders. 

The ability to parse any JSON is already in the library, but (as far as I can tell?) it's not exposed to the user. 

Perhaps we could add it to the API?

For .NET:

```fsharp
  let tryParseJsonValue (x : string) : Result<JsonValue, string> =
    try
      use reader = new JsonTextReader(new StringReader(x), DateParseHandling = DateParseHandling.None)

      let json = Newtonsoft.Json.Linq.JValue.ReadFrom reader
      Ok json
    with
      | :? Newtonsoft.Json.JsonReaderException as ex ->
        Error ("Given an invalid JSON: " + ex.Message)
```

For Fable:

```fsharp
  let tryParseJsonValue (x : string) : Result<JsonValue, string> =
    try
      let json = JS.JSON.parse x
      Ok json
    with
      | ex when Helpers.isSyntaxError ex ->
        Error ("Given an invalid JSON: " + ex.Message)
```
Then we can inject schema-less JSON into encoders quite naturally:

```fsharp
#r "nuget: Thoth.Json.Net"

open System
open Thoth.Json.Net

let innerJson =
  tryParseJsonValue "{ x: 1 }"
  |>
    function
    | Ok x -> x
    | Error e -> failwith e

let json =
  Encode.object
    [
      "id", Encode.guid (Guid.NewGuid())
      "inner", innerJson
    ]

let s = Encode.toString 2 json

printfn "%A" s

(*

"{
  "id": "bf941f23-db24-4f7d-b5a0-accf8393cd11",
  "inner": {
    "x": 1
  }
}"

*)
```

**Comment by MangelMaxime** [comment]
You can already do that with the existing API:

Indeed there is the decoder `Decode.value` which always succeed:

https://github.com/thoth-org/Thoth.Json/blob/78ea91a73fa4d3587118e040eed92a7f61b1eb06/src/Decode.fs#L538

[Live demo](https://fable.io/repl2/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSRQAqAFsAC4moBSAzsBLriuVAFb3QC8uUfUAIiEBvQQA8BALigBGKAF8hApiygBLCBDBY6DKD35QAImADGwACZoAZlmABbAMrksGgObGzltADc4SAFcwdk5efgAfAD4oawCIU3I1BjDDPnCoAHkAaxCGADV-IKgAWmiU1MMOfMK8csN0gFEsOywobRaAWTBaWjg3YNK6ipi4NSQAdzVKNubsLp6+2tUtcd1uMIb471RgBDYzcnKAbSGBNQsBABooTfMrVDcA86gACkcAT1pyMHtUAHEnhZUAA5MDjAHnF4ASihpw0WiwV3Umm0a3KAF0VGBWLR9DctvdyMBnK4IB4AExQFZo3AgUnkazQAQAUgAggIoLQgA&html=DwCwLgtgNgfAUAAlAUwIYBN4O0iyyoLhgAOAtMgI4CuAlgG4C8A5AMID2AdmMt2QCoBPEsmYIAxlx7cWPAB5gA9OGgBuCSFQAnAM75G1MADMyADmZYcwHeK20SYBDq3jGAIgD6HgBIB5AMr8XopQtABGOopaaOJgAHQkWuzo1LG0XHEQtJxxAFY6bjDAijZ2DpbY1rb2js6unj4BQR4h4ZHRqLFk6OwQCUkpaRlZOfmFxaU1FUihnADWCNFQ7jpgglDIOiDI+G5E0UbuXn6BwaERiuI6kWHUUBComdlxVwUIitPAswtLK2sbWx2YD2IAOR0apxa50ir0UqCgUCeOVeew+cGK2wwWGAYWSggkUFQ13cqBI5Ek3FQ2WQWkKiCs6AYCFo6HcyHutC2ZFJJD24kJxLc7KyXJ540UjPo8GKuPQgmxykgsCAA&css=HQYwhgTgJsCWDOBaMA3MAXSACLBvAUDjgLZgAeiA7rFOgBYBcWAzAKwAMADmQNyFGkIAc1gA7JmACu6APZ8AvoVCQYCZGkwQsy6IlikhAUzz8cUBJwA2YAJ5MAZpcO9TWAFaT46WPZuIQMqLohkFMICHBEHxEWGCWsEKiesHE8GERhlGunGBQ5qJCTABMrNxY7OUKQA)

```fs
let json =
    """{ "x": 1 }"""

let innerJson =
    Decode.fromString Decode.value json
    |> function
        | Ok jsonValue -> 
            jsonValue

        | Error errorMessage ->
            failwith errorMessage

let newJson =
  Encode.object
    [
      "id", Encode.guid (System.Guid.NewGuid())
      "inner", innerJson
    ]

let s = Encode.toString 2 newJson

printfn "%A" s
```

**Comment by njlr** [comment]
Ah! I hadn't spotted that. Thanks

**Comment by MangelMaxime** [comment]
Ahah no problem :)

TBH it tooks me 20min of writing another answer to think: Hey but don't I have a "discard" decoder already? 🤣
