### ISSUE TITLE
Start path with type name for auto decoders

### ISSUE THREAD

**Issue by alfonsogarciacaro** [thoth-org/Thoth.Json#120]
Right now, the path used in error messages starts always with `$`. The error message says what was expected when the error happened, but it's not immediately obvious where the error happens in the app. If we started the path with the type name that was being decode may make it easier. So instead of:

```
Error at $.foo.bar: Expected int but go string.
```

```
Error at MyType.foo.bar. Expected int but go string.
```

What do you think @MangelMaxime? I can open a PR if you agree with the change.

**Comment by MangelMaxime** [comment]
Personally, I don't like this idea because it imply that `MyType` is a property and so the JSON should have it included.

`$.X.X` is the standard syntax for the JSONPath. 

It is up to the user to log the error in a way that it make it explicit where it occurred in the application.

**Comment by MangelMaxime** [comment]
If you prefer that for your application, you can add your own method to the `Auto` type.

**Comment by alfonsogarciacaro** [comment]
Ah, yes, you're right. Actually I just realized the start of the path is set by `fromString` not by the decoders so anyway this has to be set externally 😅
