### ISSUE TITLE
caseStrategy doesn't affect DU case names

### ISSUE THREAD

**Issue by olivercoad** [thoth-org/Thoth.Json#122]
Using auto coders, the `caseStrategy` parameter doesn't work for discriminated union case names.

Repro:

```fsharp
#r "nuget:Thoth.Json.Net"
open Thoth.Json.Net
type Direction2 = Up | Down | Left | Right
let inline encoder<'T> = Encode.Auto.generateEncoder<'T>(caseStrategy = CamelCase)
printfn "%s" (encoder Left |> Encode.toString 4)
```

Expected "left" but result is "Left"

**Comment by olivercoad** [comment]
The docs say
> `Decode.Auto` helpers accept an optional argument `caseStrategy` that applies to keys

and DU case names are values in the json not **keys**, so I guess it's technically not a bug, but it's not what I'd expected.

**Comment by MangelMaxime** [comment]
Hello @olivercoad,

as you found `caseStrategy` control the keys. It only has effect on the record properties.

If your DUs case don't have any argument, you can convert it into a `[<StringEnum>]` in Fable.

https://fable.io/docs/communicate/js-from-fable.html#StringEnum

The rules applied to the string enum attributes will be respected:

https://github.com/thoth-org/Thoth.Json/blob/7f6b448ce9ba283b606926eace136eacc148d159/tests/Encoders.fs#L611-L631

If you never used String enum here is the types definitions used in the test above:

https://github.com/thoth-org/Thoth.Json/blob/7f6b448ce9ba283b606926eace136eacc148d159/tests/Types.fs#L252-L268

**Comment by olivercoad** [comment]
Thanks, that works for my use case.

Closing as if a DU has arguments preventing use of `StringEnum`, then it probably needs a custom encoder anyway if it needs to conform to an existing API spec.
