### ISSUE TITLE
generateDecoderCached returns the same decoder for different types

### ISSUE THREAD

**Issue by kerams** [thoth-org/Thoth.Json#123]
```fsharp
let a = """[[ "blah", 0 ]]"""
let b = """[[ 0, "blah" ]]"""
printfn "%A" (Decode.fromString (Decode.Auto.generateDecoderCached<(string * int)[]> ()) a)
printfn "%A" (Decode.fromString (Decode.Auto.generateDecoderCached<(int * string)[]> ()) b)
```

The second decode fails unless the first one is commented out.

The problem is here:

```fs
        static member generateBoxedDecoderCached(t: System.Type, ?caseStrategy : CaseStrategy, ?extra: ExtraCoders): BoxedDecoder =
            let caseStrategy = defaultArg caseStrategy PascalCase

            let key =
                t.FullName
                |> (+) (Operators.string caseStrategy)
                |> (+) (extra |> Option.map (fun e -> e.Hash) |> Option.defaultValue "")

            Util.CachedDecoders.GetOrAdd(key, fun _ -> autoDecoder (makeExtra extra) caseStrategy false t)

        static member inline generateDecoderCached<'T>(?caseStrategy : CaseStrategy, ?extra: ExtraCoders): Decoder<'T> =
            Auto.generateBoxedDecoderCached(typeof<'T>, ?caseStrategy=caseStrategy, ?extra=extra) |> unboxDecoder
```

`t.FullName` returns ```System.Tuple`2[]``` for both types. `typeof<'T>.FullName` in `generateDecoderCached` would return a string with generic type arguments plugged in, i.e. ```System.Tuple`2[System.String,System.Int32][]```.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Do you know what is happening here and if it is a Fable bug?

**Comment by alfonsogarciacaro** [comment]
It looks indeed [like a Fable bug](https://fable.io/repl/#?code=PTAEBUAsEsGdQA4CdoDsAu8DGB7JSBTLdAGwE8AodMhAnAMwB4AKWdFVAcwCpQ10AlAG0AugD4AdADEAriRIA5AIYBbAqAA+YxB3T1UoAEQBSWIao06TVuzQ9Q9EjiWDRk2fOVrN25P31GpuYUJATooOgAjKAAvBGWDCxsHPb8wuIhYREATLHxtIk2KbyOzq4ZFCAQMPBwoADuSDhcVJHScoqq6lo6-gYmZlTZ7Z5dPr0YAQOGQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYzAAYE8RAkOgBzcFYANiTLa09vXyslJxd4RBVIWDggA&css=Q) :/ I'll try to fix it.

**Comment by kerams** [comment]
All good with 3.4.9, many thanks to you both.

**Comment by MangelMaxime** [comment]
Thank you @kerams for taking the time to identify the cause on Gitter.

Thank you @alfonsogarciacaro for the quick fix :)
