### ISSUE TITLE
Add Decode.listLength, Decode.arrayLength

### ISSUE THREAD

**Issue by Swoorup** [thoth-org/Thoth.Json#131]
When you are storing varying elements in an array, it would be nicer if we can also discriminate using their length, So subsequently you could use `Decode.andThen` followed by sets of valid `Decode.index` patterns.

**Comment by MangelMaxime** [comment]
Hello @Swoorup,

To be sure, I understand could you please provide an example (JSON + F# code) of what you are trying to do?

**Comment by njlr** [comment]
This should work, although there may be potential for efficiency gains by not decoding the whole list:

```fsharp
module Decode =

  let listLength : Decoder<int> =
    Decode.list Decode.value
    |> Decode.map List.length
```

But perhaps this is better?

```fsharp
module Decode =

  let note : Decoder<_> =
    Decode.oneOf
      [
        Decode.tuple3 Decode.int Decode.string Decode.datetime
        |> Decode.map Note

        Decode.index 0 Decode.int
        |> Decode.map DeleteCommand
      ]
```

Note that order of the `oneOf` elements is significant here, since a valid `Note` can also decode as a valid `DeleteCommand`

**Comment by Swoorup** [comment]
@njlr I am using this for now, I got it from somewhere in the source code which was doing something similar.

```fsharp
  let arrayLength: Decoder<int> =
    fun path value ->
      if Decode.Helpers.isArray value then
        let vArray = Decode.Helpers.asArray value
        Ok vArray.Length
      else
        (path, BadPrimitive("an array", value)) |> Error
```

**Comment by MangelMaxime** [comment]
I am closing this issue because I think this is a specific use case.

If more people show interest in it, I will reconsider including it in the core library.

Another solution is to create a packages or gist to extends Thoth.Json and make it available to others.
