### ISSUE TITLE
DateTime-Problem

### ISSUE THREAD

**Issue by brase** [thoth-org/Thoth.Json#16]
I am not sure if I am "holding it wrong" or if there is an error.

I have some kind of server side model which gets serialized. It has a date property with the following value: `"Date\":\"2019-03-13T00:00:00\"`.

The client then deserializes it to the following value:
![image](https://user-images.githubusercontent.com/170088/58945512-48e65c00-8784-11e9-8511-62e7e1114469.png)

Why is it doing that?

**Comment by MangelMaxime** [comment]
The date you see in the console is the one called "LocalTime" (that's the behaviour or `Date` type in JavaScript).

But if you try to access the `Hour` property then you should get `23` as expected.

For example, if I run this code:

```fs
let json =
    """
{
    "Date": "2019-03-13T00:00:00"
}
    """

let res = 
    Decode.unsafeFromString (Decode.field "Date" Decode.datetime) json

JS.console.log("Res: ", res)
JS.console.log("Hour: ", res.Hour)
```

[REPL url](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNSATKXAGICGARrFsYSAE416jOABUMIStgBSaEKVqxKcAFaymAXmpxtcAET7qAby07dAEVaUYugFx6ATAAYAjAE4AtI4DM7515GOjjaBwY661AC+Jtr64dSKcHwwaHDqcNFwZjAAxuAwWBCkaKwAZjDMfCDAOJR8KKQA5nAAFFm5YPklKDBQYHoWVrqZOXlYYJYwlPgwAJQqarRSOFi5RSBcUCANzboASsl2ugA0ickz1EsrcrIbWzsAEiAQfIcnSWhYj88zQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

I got this output in the console:

```
[Log] Res:  – Wed Mar 13 2019 01:00:00 GMT+0100 (CET)  (blob:https://fable.io/fa29b05b-d349-40a2-b224-4a23404c6b96, line 27)
[Log] Hour:  – 0 (blob:https://fable.io/fa29b05b-d349-40a2-b224-4a23404c6b96, line 27)
```

The first line show the "LocalTime" display. But when I access the `Hour` property I get `0` as expected.

**Comment by brase** [comment]
Okay, thank you. 

Seems I have to live with it.
