### ISSUE TITLE
How to decode a result with a list of DU?

### ISSUE THREAD

**Issue by Slesa** [thoth-org/Thoth.Json#184]
I am trying to implement a Command/Event system via Giraffe. The command is a 'turnon 1' and works fine, the result is a Result<Event list, Error>. The json looks like

```json
[
  "Ok",
  [
    [
      "TurnedOnEvent",
      {
        "sessionId": "378cb85c-3aa7-4016-acfe-c371f0b61898"
      }
    ]
  ]
]
```

What I've tried so far:
```fs
    type TurnedOnEvent =
        {
            sessionId: Guid
        }
        static member decode =
            Decode.field "sessionId" Decode.guid |> Decode.map (fun x -> { sessionId = x })
        static member encode (turnOff: TurnedOnEvent) =
            Encode.object [
                "sessionId", Encode.guid turnOff.sessionId
            ]
    type PosEvent =
        | TurnedOnEvent of TurnedOnEvent
    module PosEvent =
        let decodeTurnedOnEvent =
            Decode.field "TurnedOnEvent" TurnedOnEvent.decode |> Decode.map TurnedOnEvent
        let decoder: Decoder<PosEvent> =
            Decode.oneOf [
                    decodeTurnedOnEvent //; decodeTurnedOffEvent
            ]
        let encoder (event: PosEvent) =
            match event with
            | TurnedOnEvent turnOn ->
                TurnedOnEvent.encode turnOn

module PosError =
    
    type ErrorCode =
        | SessionNotFound
        | TerminalNotFound
        
    type Error = {
        Code: ErrorCode
        Msg: string
    }

```

But how can I use these decoders with the Result decoder and then with the list? Is it enough to declare them as extra decoders, oder do I call them manually?

```fs
        let decoder: Decoder<Result<PosEvent, PosError.Error>> =
            Decode.string
            |> Decode.andThen (function
                | "Ok" ->
                    ? Decode.object PosEvent.decodeTurnedOnEvent |> Decode.map (Ok(TurnedOnEvent))
                | "Error" -> 
                    ? Decode.Auto.fromString x
                | _ -> Decode.fail "Syntax error in string")
```

Something like this, or is this the wrong way? Or would it be bad practice at all?

**Comment by MangelMaxime** [comment]
Hello @Slesa,

The problem with your current decoders is that you are trying to access a field `TurnedOnEvent` (`Decode.field "TurnedOnEvent"`) when your JSON is not using an object but a list where the first element is the name of the DU and the second is the actual value.

Examples on how to decode such DUs can be found [here](https://thoth-org.github.io/Thoth.Json/documentation/manual/json-representation.html#discriminated-union) in the documentation.

Here is an example of how to work with your JSON:

```fs
open Fable.Core
open System
open Thoth.Json

let json =
    """
[
  "Ok",
  [
    [
      "TurnedOnEvent",
      {
        "sessionId": "378cb85c-3aa7-4016-acfe-c371f0b61898"
      }
    ]
  ]
]
    """

type TurnedOnEvent =
    {
        sessionId: Guid
    }
    
module TurnedOnEvent =

    let decoder : Decoder<TurnedOnEvent> =
        Decode.object (fun get ->
            {
                sessionId = get.Required.Field "sessionId" Decode.guid
            }
        )

type PosEvent =
    | TurnedOnEvent of TurnedOnEvent

module PosEvent =

    let decoder : Decoder<PosEvent> =
        Decode.index 0 Decode.string
        |> Decode.andThen (function
            | "TurnedOnEvent" -> 
                Decode.index 1 TurnedOnEvent.decoder
                |> Decode.map TurnedOnEvent
            | unknown ->
                sprintf "Unknown type for PosEvent : '%s'" unknown
                |> Decode.fail 
        )

module Envelop =

    let decoder : Decoder<Result<PosEvent list, string>> =
        Decode.index 0 Decode.string
        |> Decode.andThen (function
            | "Ok" ->
                Decode.index 1 (Decode.list PosEvent.decoder)
                |> Decode.map Ok
            | _ ->
                Decode.succeed "Invalid envelop"
                |> Decode.map Error
        )

match Decode.unsafeFromString Envelop.decoder json with
| Ok data ->
    printfn "Numbers of events: %d" data.Length
| Error error ->
    failwith error
```

[REPL link](https://fable.io/repl2/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSRQDKAngM4AuYAtvuNACoAWwFTqAUmcBLrihSgArbtAC8uKFKgAiObgDak2QHkA1jIA0ypdKi69shgFcsEMABMVEAKIA3SBS3K9AbxeGZZMGTIBLHgBJCxkALlkAZgB2AA4AYwQYgFY4gFoIuDgo1IAWAAYARgA2VLg4gDMwVLjogvK8hCKCmIBOGJkPKQBfDwBdZX7+vTkO3AoScCgTM0tre0coCTdO6W9fAIhg8IBxYz8LDx69XGpgC2MUKdNzK1sHCEEJDwEoCzA4s7AsKHCAEXfPlgADzTG5ze4UAB8ixWUn+HzeqGACCE70EAApysZoABzMCCVKQ2GGdyGMmGNb+IIWRZQPEUVAAJTAAEc9jgLKgYH4wEgaV4fFTNiEoPDPqgcXsDuTDEdyQBKPjjSYABWAZHmDxhegAPlcZrdNYJgOV9WC7o4+Kdzpc1RqITDnvjXgC3t8-q6vkC7UboUtyWLEX4IG8AB5QPKiz2oShYYM44k66GBtBwEPMQiY7FxCgbYm6ozXWYWh4yKCEqD5gPR4NhqAFM3Fo2oN4Ir5VslJqNt1DUOAgRuGiEdqB67FqCDAADu0EJI70ZBAcYeppkAFUIBPp9BlWAoOVsFAfQ7wgByACkZFPZfHk5n8+kXZTqHKcD8SErMsVJzOFz3NggBwkFAR09BeVtAR+btASBZkyAuChvXVI0oCQPxKE0KBY3jSE-WJZ9azAcNI2fbCIATGUn2jNMLAzaAswgHM8xlAsZHUMs5xY6se0I8MG3RZ80MoI9kIhFtPSwRUuM7ZNoz7Ad1BHPUAH1yyJaTDFI4w4jiMBLFkQJALgNCaUgIDQA6DTdVknt5KgGwsCwbBiW-PsKDiJhoMRbEyDgSoYCc6giAoZccXswDeVAcS22+EQeCgKc-DYXA9XUV44AoOA1I8JdgwocpoBkAA5YxqAQL4yCgE0oDACEyHCc8RQsDK4FQAAZSAcWSvUHKc74vj67K9Ffd9ErYGrHOwIA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q)

**Comment by Slesa** [comment]
Thanks a lot. Yes, I ignored the list as I had absolutely no idea how to concatenate all decoders, Envelope - List - DU.

**Comment by MangelMaxime** [comment]
I am closing as I think the issue has been answered.

If you need something else feel free to comment
