### ISSUE TITLE
Help required: Move field

### ISSUE THREAD

**Issue by davedawkins** [thoth-org/Thoth.Json#186]
I have this JSON on disk
```json
{
       "foo": [ "cat", "dog" ]
}
```

which maps to type 

```fs
type Thing = { foo : string[] }
```

I have changed Thing to be

```fs
type Thing = { foo : string[]; bar : string [] }
```

and now the `foo` on disk must go into `Thing.bar` (and `Thing.foo` will be empty)

I know how to handle `bar` being missing, by using custom decoders, but cannot figure out how to write
a `Thing` decoder which can read `foo` into `Thing.bar` if `bar` is missing in the JSON.

Thank you

**Comment by njlr** [comment]
Perhaps something like this?

```fsharp
#r "nuget: Thoth.Json.Net, 11.0"

type Thing = { foo : string[]; bar : string [] }

module Thing =

  open Thoth.Json.Net

  let decode : Decoder<Thing> =
    Decode.object
      (fun get ->
        {
          foo = get.Required.Field "foo" (Decode.array Decode.string)
          bar =
            get.Optional.Field "bar" (Decode.array Decode.string)
            |> Option.defaultValue [||]
        })
```

**Comment by MangelMaxime** [comment]
Hello @davedawkins,

I am not sure to understand everything. Could you please provide the expected values associated to the JSON?

For example:

```fs
type Thing = { foo : string[]; bar : string [] }

let json =
    """
{
       "foo": [ "cat", "dog" ]
}
    """

let expected =
    {
        foo = [ "cat", "dog" ]
        bar = []
    }
```

If there are different scenario I would be interested in having them too.

**Comment by davedawkins** [comment]
My best effort 

```fs

**Comment by njlr** [comment]
I think you want `Decode.oneOf`

```
let decoderThing = 
  Decode.oneOf 
    [
       decoderV2
       decoderV1
    ]
```

Beware that the order matters here! It will attempt `decoderV2` first and only try `decoderV1` if that fails.

**Comment by davedawkins** [comment]
Beautiful thank you

**Comment by davedawkins** [comment]
Can confirm this works, thank you so much
```fs
    let decoder : Decoder<EntityDTO> =
        Decode.oneOf [
            Decode.Auto.generateDecoder<EntityDTO>()
            Decode.Auto.generateDecoder<EntityDTO_v1>() |> Decode.map mapE1E2
        ]
```
