### ISSUE TITLE
Add lenient option for auto coders

### ISSUE THREAD

**Issue by alfonsogarciacaro** [thoth-org/Thoth.Json#24]
I see that auto coders are failing most of the times for the Elmish debugger. It'd be nice to have a "lenient" (or "forgiving") option for auto coders to just ignore the fields that Thoth doesn't know how to serialize. This way the debugger would be usable (although time traveling may not work correctly).

**Comment by alfonsogarciacaro** [comment]
This shouldn't be difficult to implement, I can send a PR.

**Comment by MangelMaxime** [comment]
This is kind of opposite to Thoth.Json goal, this also means that when using the Elmish debugger you will see an incorrect/incomplete version fo your application.

If the "problem" is Elmish debugger, why not make it fallback to raw `JSON.stringify` if `Thoth.Json` fails to encode it?
