### ISSUE TITLE
Error not reported if it's an optional field

### ISSUE THREAD

**Issue by MangelMaxime** [thoth-org/Thoth.Json#3]
```fs
type Config =
    { MenuConfig : MenuConfig option }

    static member Decoder =
        Decode.object (fun get ->
            { MenuConfig = get.Optional.Field "menu" menuConfigDecoder }
        )
```

If there is an error inside `menuConfigDecoder` it's returning `None`. I think we should return an Error because the field was in the JSON but in an incorrect form.

**Comment by alfonsogarciacaro** [comment]
Hmm, strange. It should work as you say. Could please add a full example to debug it?

**Comment by MangelMaxime** [comment]
I didn't test this code with the beta version of `Thoth.Json`.

I am still using version `2.5` so perhaps it has been fixed in the beta version. Will post the reproduction code later.

**Comment by MangelMaxime** [comment]
#2 should fix this problem. I will re-open if I still have it in my project.
