### ISSUE TITLE
Support enum for auto encode and decode

### ISSUE THREAD

**Issue by albertwoo** [thoth-org/Thoth.Json#31]
I have below code and use Encode.Auto failed for enum types, can we support it by default or it does support but after fable compiler 2.4.4 (WIP: Feature/add enum reflection) the feature is broken?
```fsharp
type Status =
    | On = 1
    | Off = 2

type App =
  { Id: int
    Name: string
    Status: Status
    Progress: float option
    StartedDate: DateTime }
  static member defaultValue =
    { Id = 1
      Name = "a1"
      Status = Status.On
      Progress = Some 0.2
      StartedDate = DateTime.Now }

let thothJson = Thoth.Json.Encode.Auto.toString(4, App.defaultValue)
Browser.Dom.console.error(thothJson)
Browser.Dom.console.error(Thoth.Json.Decode.Auto.fromString<App>(thothJson))
```

Error message:
`Uncaught Error: Cannot generate auto encoder for Client.App.States.Status[System.Int32]. Please pass an extra encoder`

**Comment by MangelMaxime** [comment]
The support for all the enum supported by Fable (numeral only except for int64) is being working on in https://github.com/thoth-org/Thoth.Json/pull/28

The next version of the library will include it. I still have a few things to finish before releasing a new version.

**Comment by albertwoo** [comment]
Great to hear. Thanks!
