### ISSUE TITLE
On serializing/deserializing a DateTime, "Kind" information is lost and is set to UTC

### ISSUE THREAD

**Issue by MangelMaxime** [thoth-org/Thoth.Json#41]
<a href="https://github.com/sachabroute"><img src="https://avatars3.githubusercontent.com/u/3247529?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sachabroute](https://github.com/sachabroute)**
_Thursday Jul 25, 2019 at 11:00 GMT_
_Originally opened as https://github.com/MangelMaxime/Thoth/issues/156_

----

When serializing a DateTime CEST, on deserializing we lose the "Kind" information and it is set by default to UTC.

Client:
![image](https://user-images.githubusercontent.com/3247529/61869465-fa2f8580-aedb-11e9-9715-5b8c0c334807.png)

Server: 
![image](https://user-images.githubusercontent.com/3247529/61869497-09aece80-aedc-11e9-84ea-29f9ff220d9c.png)

**Comment by MangelMaxime** [comment]
<a href="https://github.com/MangelMaxime"><img src="https://avatars0.githubusercontent.com/u/4760796?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MangelMaxime](https://github.com/MangelMaxime)**
_Thursday Jul 25, 2019 at 11:16 GMT_

----

By default, we transfer UTC over the JSON because your client and server can be on a different timezone. I think this is what most JSON serialize do but can be wrong.

In general, if you need a specific `DateTime` handler, you should write your own.

It's also possible that `DateTimeOffset` is a solution for that too, I don't know. Handling date is really complex :)

**Comment by MangelMaxime** [comment]
<a href="https://github.com/sachabroute"><img src="https://avatars3.githubusercontent.com/u/3247529?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sachabroute](https://github.com/sachabroute)**
_Thursday Jul 25, 2019 at 11:51 GMT_

----

Makes sense, I was also thinking it might have been done deliberately as server should always have the UTC time.
However it seems there is some ambiguity as to other JSON serializers do since I think Newtonsoft.Json does deserialize the Kind properly, but Microsoft's don't.
Maybe this could deserve some kind of note somewhere?

**Comment by MangelMaxime** [comment]
<a href="https://github.com/MangelMaxime"><img src="https://avatars0.githubusercontent.com/u/4760796?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MangelMaxime](https://github.com/MangelMaxime)**
_Thursday Jul 25, 2019 at 11:54 GMT_

----

> Maybe this could deserve some kind of note somewhere?

We can add that to the doc comment [here](https://github.com/thoth-org/Thoth.Json/blob/master/src/Encode.fs#L302) and [here](https://github.com/thoth-org/Thoth.Json.Net/blob/master/src/Encode.fs#L183).

Note that the projects are in a separate repo.

The split of this repo isn't complete yet.

**Comment by nirvinm** [comment]
Thoth.Json should not assume that the DateTime sent from server should always be in UTC. There are many cases where local DateTime will be sent (like alarm time). 

Unless the server sends timestamp with the `Z` specifier (ex. `2021-03-03T09:30:00Z`) or with the timezone difference (ex. `2021-03-03T09:30:00−02:00`), Thoth.Json should return the DateTime with `Kind`  set to `Unspecified`. IMO, this is the correct behavior.

.NET and Fable already behaves as expected.

    DateTime.Parse("2021-03-03T09:30:00")     // DateTime.Kind is Unspecified
    DateTime.Parse("2021-03-03T09:30:00Z")    // DateTime.Kind is Local

However in Decode.fs

```
let datetime : Decoder<System.DateTime> =
    fun path value ->
         if Helpers.isString value then
             match System.DateTime.TryParse (Helpers.asString value) with
             | true, x -> x.ToUniversalTime() |> Ok
             | _ -> (path, BadPrimitive("a datetime", value)) |> Error
```

Is the `x.ToUniversalTime()` required? 

I'm not sure what's motive of doing this conversion so I maybe wrong too.

**Comment by MangelMaxime** [comment]
In PR #149, we the `Decode.datetime` as being marked as obsolete to make it explicit was is happening to the date.

I think this also fix the issue too.
