### ISSUE TITLE
Missing keyword in documentation

### ISSUE THREAD

**Issue by gsscoder** [thoth-org/Thoth.Json#50]
Nothing really important, just to help...

In this document;
https://thoth-org.github.io/Thoth.Json/#Object-builder-style
paragraph;
Object builder style

Lacks `with` before member definition.

Have a nice day

**Comment by MangelMaxime** [comment]
Depending on how you indent your code the `with` keyword is optional. 

If you copy/paste the snippet the compiler should be happy.

**Comment by gsscoder** [comment]
Cool! I thing I was missing...
