### ISSUE TITLE
Compile Error while compiling Thoth.Json with Fable 3.1.4

### ISSUE THREAD

**Issue by l3m** [thoth-org/Thoth.Json#52]
I'm trying to build a safe stack app and get this error: 

ERROR in ./.fable/Thoth.Json.3.4.1/Decode.fs
Module Error (from ./node_modules/fable-loader/index.js):
/Users/l3m/Documents/Devel/funui/.fable/Thoth.Json.3.4.1/Decode.fs(25,52): (25,60) error FSHARP: This construct is deprecated. JS constructors are now in Fable.Core.JS.Constructors module to prevent conflicts with modules with same name (code 44)

- macOS 10.15
- dotnet-sdk 3.1.100
- Fable.Core 3.1.4

**Comment by MangelMaxime** [comment]
Thank you for reporting, I will release a new version later today.

**Comment by MangelMaxime** [comment]
I just checked when compiling against `Fable.Core 3.1.4` I get:

```
C:/Users/mamangel/Documents/Workspace/Github/thoth-org/Thoth.Json/src/Decode.fs(25,52): (25,60) warning FSHARP: This construct is deprecated. JS constructors are now in Fable.Core.JS.Constructors module to prevent conflicts with modules with same name (code 44)
C:/Users/mamangel/Documents/Workspace/Github/thoth-org/Thoth.Json/src/Decode.fs(30,50): (30,59) warning FSHARP: This construct is deprecated. JS constructors are now in Fable.Core.JS.Constructors module to prevent conflicts with modules with same name (code 44)
C:/Users/mamangel/Documents/Workspace/Github/thoth-org/Thoth.Json/src/Decode.fs(51,68): (51,77) warning FSHARP: This construct is deprecated. JS constructors are now in Fable.Core.JS.Constructors module to prevent conflicts with modules with same name (code 44)
```

Which are warning only. I think you have a flag in your configuration which say "treat warnings as errors".

**Comment by MangelMaxime** [comment]
The Fable.Core 3.1.4 upgrade is available in Thoth.Json 3.5.0

**Comment by l3m** [comment]
Great - thanks a lot for the quick fix!
