### ISSUE TITLE
Extra coders not activated when generating an autocoder

### ISSUE THREAD

**Issue by kzbt** [thoth-org/Thoth.Json#66]
Related to https://github.com/thoth-org/Thoth.Json.Giraffe/issues/11

I'm trying to use a custom encoder and decoder with "extra". But it doesnt seems to work. 

Below is the code and a test case
```fsharp
type ApiResponse<'t> =
  | ApiData of 't
  | ApiError of list<string * VError>

  static member Encoder =
    function
    | ApiData d ->
      let encoder = Encode.Auto.generateEncoderCached<'t>()
      Encode.object ["data", encoder(d)]
    | ApiError errors ->
      let encoder = Encode.Auto.generateEncoderCached<VError>()
      let jsonErrors = List.map (fun err -> Encode.object [(fst err), encoder (snd err)]) errors
      Encode.object ["errors", Encode.list jsonErrors]

  static member Decoder: Decoder<ApiResponse<'t>> =
    let dataDecoder =
      Decode.object (fun get ->
        Decode.Auto.generateDecoderCached<'t>()
        |> get.Required.Field "data"
        |> ApiData)

    let errorsListDecoder = Decode.Auto.generateDecoderCached<VError>() |> Decode.keyValuePairs
    let errorsDecoder =
      Decode.object (fun get ->
        errorsListDecoder
        |> get.Required.Field "errors"
        |> ApiError)

    Decode.oneOf [dataDecoder; errorsDecoder]
```

**Test**
```fsharp
type Person = { Name: string }

[<Tests>]
let tests =
  testList "coders" [

    let extraCoders =
      Extra.empty
      |> Extra.withCustom ApiResponse.Encoder ApiResponse.Decoder

    test "api response should encode data" {
      let expected = """{"data":{"name":"K"}}"""

      let person = { Name = "K" }
      let res = ApiData person
      let encoder = Encode.Auto.generateEncoderCached<ApiResponse<Person>>(extra = extraCoders)
      encoder res
      |> Encode.toString 0
      |> printf "%s"  // prints ["ApiData",{"Name":"K"}]
    }
  ]
```

**Comment by MangelMaxime** [comment]
Hum, the problem is not that they are not activated.

The problems come from the fact that the Auto modules don't allow you to override the default encoder/decoder knows by Thoth.Json.

Basically, when Thoth.Json encounter your type `ApiResponse` it directly applies the default DU decoder to it and not your custom one.

**Comment by kzbt** [comment]
I see. So If I want to use custom encoders I should do something like this I believe
``` fsharp               
let jsonStr = ApiResponse.Encoder res |> Thoth.Json.Encode.toString 0
```

Also I think the documentation might be misleading in this case. It says extra can replace the default coders.
>In those cases you can pass extra coders that will replace the default (or missing) coders

**Comment by MangelMaxime** [comment]
Well, I think it will replace it if it is a record but not in the case of the DUs.

More tests are needing in order to affirmate that. TBH I never use the Auto modules because I don't like reflection so I am not really used to working with them :)
