### ISSUE TITLE
vNext - Support lossless option

### ISSUE THREAD

**Issue by MangelMaxime** [thoth-org/Thoth.Json#81]
Original issue: https://github.com/thoth-org/Thoth.Json.Giraffe/issues/15

> 
> 
> Hum, I guess the problem comes from the fact you are using `'T option option`.
> 
> And we kind of erase the `option` type to a really simple representation:
> 
>     * If `Some ...`, it outputs directly the value
> 
>     * If `None`, it uses `null` or the absence of the value/property field.
> 
> 
> So when nested several `option` we lose some information
> 
> ```fsharp
> open Fable.Core
> open Thoth.Json
> 
> let someValue : string option= Some "Maxime"
> let noneValue : string option = None
> let someSomeValue : string option option = Some (Some "Maxime")
> let someNoneValue : string option option = Some None
> let deeplyNestedValue : string option option option option option = Some (Some (Some (Some None)))
> 
> JS.console.log(Encode.Auto.toString(4, someValue)) // "Maxime"
> JS.console.log(Encode.Auto.toString(4, noneValue)) // null
> JS.console.log(Encode.Auto.toString(4, someSomeValue)) // "Maxime"
> JS.console.log(Encode.Auto.toString(4, someNoneValue)) // null
> JS.console.log(Encode.Auto.toString(4, deeplyNestedValue)) // null
> ```
> 
> I am working on Thoth.Json 5 which is already doing some changes to how it represents some types perhaps we should make a custom representation for `option` type in order to retain the information. It will increase the JSON size but avoid losing information.
> 
> Right now, unless you copy/paste/adapt the code of the Auto modules you can't use it to solve your problem. However, you should be able to write your own `Encode.option` and `Decode.option` to have the desired behaviour I think.
> 
> Prototype:
> 
> _There is a lot of code and I didn't focus on making it pretty just wanted to provide some hint for a potential solution. I think by using some helpers etc. it could look much better ^^_
> 
> ```fsharp
> open Fable.Core
> open Thoth.Json
> 
> 
> // Standard behaviour from Thoth.Json Auto modules
> module Standard =
>     let someValue : string option= Some "Maxime"
>     let noneValue : string option = None
>     let someSomeValue : string option option = Some (Some "Maxime")
>     let someNoneValue : string option option = Some None
>     let deeplyNestedValue : string option option option option option = Some (Some (Some (Some None)))
> 
>     JS.console.log(Encode.Auto.toString(4, someValue)) // "Maxime"
>     JS.console.log(Encode.Auto.toString(4, noneValue)) // null
>     JS.console.log(Encode.Auto.toString(4, someSomeValue)) // "Maxime"
>     JS.console.log(Encode.Auto.toString(4, someNoneValue)) // null
>     JS.console.log(Encode.Auto.toString(4, deeplyNestedValue)) // null
> 
> module Custom =
> 
>     let log x = JS.console.log x
> 
>     module Encode =
> 
>         let losslessOption (encoder : 'a -> JsonValue) =
>             fun value ->
>                 match value with
>                 | Some value ->
>                     Encode.object 
>                         [
>                             "$type$", Encode.string "option"
>                             "$state$", Encode.string "Some"
>                             "$value$", encoder value
>                         ]
> 
>                 | None ->
>                     Encode.object 
>                         [
>                             "$type$", Encode.string "option"
>                             "$state$", Encode.string "None"
>                         ]
> 
>     module Decode =
>         
>         let losslessOption (decoder : Decoder<'value>) : Decoder<'value option> =
>             Decode.field "$type$" Decode.string
>             |> Decode.andThen (fun typ ->
>                 match typ with
>                 | "option" ->
>                     Decode.field "$state$" Decode.string
>                     |> Decode.andThen (fun state ->
>                         match state with
>                         | "Some" ->
>                             Decode.field "$value$" decoder |> Decode.map Some
> 
>                         | "None" ->
>                             Decode.succeed None
>                         
>                         | invalid ->
>                             "Expected an object with a field `$state$` set to `Some` or `None` but instead got `" + invalid + "`"
>                             |> Decode.fail 
>                     )
> 
>                 | invalid ->
>                     "Expected an object with a field `$type$` set to `option` but instead got `" + invalid + "`"
>                     |> Decode.fail 
>             )
> 
>     let someValue : string option= Some "Maxime"
>     let noneValue : string option = None
>     let someSomeValue : string option option = Some (Some "Maxime")
>     let someNoneValue : string option option = Some None
>     let deeplyNestedValue : string option option option option option = Some (Some (Some (Some None)))
> 
>     Encode.toString 4 (Encode.losslessOption Encode.string someValue)
>     |> log
> 
>     Encode.toString 4 (Encode.losslessOption Encode.string noneValue)
>     |> log
> 
>     Encode.toString 4 (Encode.losslessOption (Encode.losslessOption Encode.string) someSomeValue)
>     |> log
> 
>     Encode.toString 4 (Encode.losslessOption (Encode.losslessOption Encode.string) someNoneValue)
>     |> log
> 
>     Encode.toString 4 (Encode.losslessOption (Encode.losslessOption (Encode.losslessOption (Encode.losslessOption (Encode.losslessOption Encode.string)))) deeplyNestedValue)
>     |> log
> 
>     match Decode.fromString (Decode.losslessOption Decode.string) (Encode.toString 4 (Encode.losslessOption Encode.string someValue)) with
>     | Ok value ->
>         match value with
>         | Some value ->
>             printfn "Got a Some ... %A" value
>         
>         | None ->
>             printfn "Got a None"
> 
>     | Error err ->
>         JS.console.error err
> 
>     match Decode.fromString (Decode.losslessOption Decode.string) (Encode.toString 4 (Encode.losslessOption Encode.string noneValue)) with
>     | Ok value ->
>         match value with
>         | Some value ->
>             printfn "Got a Some ... %A" value
>         
>         | None ->
>             printfn "Got a None"
> 
>     | Error err ->
>         JS.console.error err
> 
>     match Decode.fromString (Decode.losslessOption (Decode.losslessOption Decode.string)) (Encode.toString 4 (Encode.losslessOption (Encode.losslessOption Encode.string) someSomeValue)) with
>     | Ok value ->
>         match value with
>         | Some (Some value) ->
>             printfn "Got a Some (Some %A)" value
>         
>         | Some None ->
>             printfn "Got a Some None"
> 
>         | None ->
>             printfn "Got a None"
> 
>     | Error err ->
>         JS.console.error err
> ```
> 
> [REPL demo](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQokUAKgBbAAuZqAUgM7AQEv4D0bUAypXBACZws-KAjBk4ANwCWwAK5YoAMyzAAtqQrU6jaAEE5lYFDXB+clPQKnzKbrwFCRAXgJR3UFJSiM1YAGpwSHJgUABcPpRY0hAA5lCglLIQztzqoQBEALJwAB7SfhluHl5QEEwBQSHhkdFxCSBJTFCpAHIVxe6lvmBc6YHBoRH0UTHxickNTdCpfX5QABRzmTn5hQCUnZ5g3j3tEJWDNSN1442TE82z6VD7ePge2978YGAgSACerWAjYPwD1WGo3ql2goKmF3OzXB13mSxu8Lhy1uFXWaNYj1oXFQAGMmIwUKgkMBYgsAKIQPEvVAGIyoIw8U4LAAsABofP0qmA0VAOFBsnkCmAig8PFjcfjgITiaSKVS0LTgPTgIyxiz2eUDgDueteZwIBYkFtxXiIAS0DLyZSzArDEqGcDSWyOX5ltqeXyBWthcbsabzUSSVb5TS7crVXF1S6wHd3bq+QakEbRe4TZLpUG5TbQ3SHUznS83p9vr9-lyPfrDawbBZQug5CN1C0MSUdp4SVBci0oGmzVKLR3ci33DW7FmXs38FtHqVifR6JZ6AB5KHQBaQeWKCIAcjgUAAtAA+Hu6d2Tx4XjxKOTQSRcg+H6eXi9qOCUHFkKB3o4Ad2k1CfZ8PAAHzSeZv2qI9AKAi9xzQYAEAAKzAHFvGgmDnwAbXQjCYIyAASSgPnAfCMnZODUBOMZ+VBEVcPoi8CJGN8wFI8jrWpKj6gyZY6IY-iCIg1iyKgDcbUUIScP4gBdYcGNAu4HykmCKIQ5DUKgZT6OwlN+NwgiiJIkSKK4+IMlorS9KY3hKGE9iQ1M-k7j4vTn1kqddNHUIABEUJtc9n2g2dgHnRcV2mRYXk3GpfM3AAebchMPXUIli8SEqEiEmGPVxdKAtLqSUaQwCQEQDOI4SoAKtBTOU4Dj2q1A+H4chiAWa9oEMpS8tw1930-Lq-wAnqMNA8zVwybrXMeRqipKsr8OY2zSKqvzOMdSzL3q1aQ2a1q1w6yIWKm6bLz6j8jtsqAhrITaYLG3iTtO-K1rQObSv5fChJWqLxKgbbGtfEAwPuO6gLG5ynuey9GvoOQcRxV4RDuMHApG6bQJib9pBEKD0ehjIyVycBUL+KA+ASJCUO8G7yeUYqPoAA0WmzWMZnw2yMKBGeWdnsG5u52YQQwoBiX44BEWIqG5yaAGpRYgbGRHljJGZc6GLwB17UCUOBpCQTT8dwzYPNczHFaCHGodcwniepsmKbU6nrv-T893ekRmcMtmOe8LnGdBIWRbF2yJagKXvDVqB5axy3lf5NXUfcLWQ11-XDfok2tm6TkjiBU4spSEH+VWIV1dKTVDkBWpqJhFEDmztsejde989r1dC+7ZFERWQUNkb3Z0ljVua5BDu6+RFHdNKQt3i+H5bLLPPR7OCLwXX8eO9hUIe8WbvJ9RdFTY8Ci82o5lFgoucFx+ZcO5Mx1o3dLZtplOTT5VR+L+DbNr7C++OI1UfpXZ+ulX4knfoA8MX9L5QL-rfcKkwf7UngfORBzQH6nF1M3XOIQTaPHAbESBIYz71G-lfEKN80Ed2QQOUKCCAEOUdNgoeFRQEEOPG-Y+7gP4RniOQuBlD-4RVoYGeh1CREUPEXfSRgjpHoLXFIqhMjJiYLGGiHks9iwLz+OwkCnCIHcJMG+C6s1VBqD4YsRqqCVHNFhsw2BJDP4FwESGGxCioBqPqD0OMLthoEKgEuAA1l+e8eMgLnU-JlG60FQLIkyuE3CIA6iUCUNADIABxaWe5kSoDyVAAApHoSakl0axPrqERJGFkkxFSekrJ3g9zOTkqBMkWBVCKDAO062Yo-TpjQF0jpol2lyUiTtbMKh1CWIWNYoRDCIr2KwY47MpD+HLJQXMiRqioGORAeWXUMSwGBJCQkx86MxnRNduU+JYSzn0RqRAOp-IGl01yfkopJSuTQXKYpKpMEHlPMydkipIoX6ePafzQZPTUx9L7ISQZkKRlGLGWYqZj8Zna3cTQ2Z8iO6LPUbqURqyoCuN-ps2xii5HKI8V42ILDXS4J1H426RzgmhKOH8x4Fz7yHPBsXXeQldScufACtJzzgX7xuEU9YnzBjfPRnEm4vy7lJJSWKoFjTi7NKMQE5VylRX1OBdqsFbShlQuFTCiUcKBkQs6e0oAA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAWAChgMcDi0kBDMclFYGASxmyVwDEqAjNlAahQAlJFDRUATjADOwAPTNW7IvWCYkMKuhgwEAWiQBHAK5MAbgF4A5AGEIAOxhJHegCqIkVlFAdPH1pwAPGDlSbABub3EJaQ0LYxgAMz0ADis6BnVNFHsqdQsAIjMmJAB3BAgpAu9fZxhC0qYwGDQLMCRiqCQ9Rua0ABoUJnsWJipsPWkocaQLAEYCjOApiSYEGBRpCShCgH1dgAkAeQBlV325bCZuaTkJalgAOgQJCDBjWCYHR8xhx4AraSLeQrNYwJag9abbZ7Q6nc67S7XW73KiwPSQTDPV7vT7fX72AFA3AgqCrdYQslg7yvaTSSpMADmw2hOwKGF00gAXHI5MZ7AgANaMx4+TByF4QfTwZDSAACcwArI8AGwS17SjzSH5-QHAuSQ8EqBiGmkQOkM5n2VmFDkIbm8-lCkViu4PGB6QEOPSaXhIOUABkec2Dcm4pmwYDdaI9XvsPp4bCJ+sN5HklBoae4bzgSzA5iGYEKPkcVGGSAkCxJcnzZkp5I2WzZ4fsYCTeurqaI8mzYFz3dCWDwQA&css=Q)

**Comment by joprice** [comment]
A related issue I hit is being able to distinguish at least the top level presence of a field for things like a patch api where you want a ternary: present / absent / null, to allow distinguishing a field that should be unset versus one that is not being passed. I'm currently using a type `Clearable` that emulates this in my custom myriad generator.

**Comment by njlr** [comment]
A good search term is "skippable" e.g. https://github.com/Tarmil/FSharp.SystemTextJson/blob/master/docs/Format.md#skippable
