### ISSUE TITLE
Thoth.Json's Code Sample does not compile

### ISSUE THREAD

**Issue by kurt-mueller-osumc** [thoth-org/Thoth.Json#98]
Thoth's [Code Sample](https://thoth-org.github.io//Thoth.Json/#Code-sample) won't compile.

The compiler throws several errors:

```
Thoth.Json.Net is not defined.
```
and

```
The type 'Decoder' is not defined in 'Thoth.Json.Decode'.
```

<img width="219" alt="Screen Shot 2021-02-05 at 10 13 48 AM" src="https://user-images.githubusercontent.com/66080261/107052142-4cbd5380-679b-11eb-99fd-b0bd9dc5ba87.png">

<img width="840" alt="Screen Shot 2021-02-05 at 10 15 18 AM" src="https://user-images.githubusercontent.com/66080261/107052148-4fb84400-679b-11eb-874a-35ea24bd1e91.png">

**Comment by kurt-mueller-osumc** [comment]
Turns out I needed to add the `Thoth.Json.Net` nuget package in order to `open Thoth.Json.Net`. *facepalm* I will say, however, that the `Thoth.Json.Net` nuget package is not mentioned anywhere in the documentation page: https://thoth-org.github.io/Thoth.Json/index.html

However, `Decode.Decoder` still throws a compiler error as well as the object attribute whitespace alignment. I've opened up a pull request [here](https://github.com/thoth-org/Thoth.Json/pull/99) and [here](https://github.com/thoth-org/Thoth.Json/pull/100).

**Comment by MangelMaxime** [comment]
Hello @kurt-mueller-osumc Thoth.Json.Net is mentioned in the section `.Net & NetCore support`

https://thoth-org.github.io/Thoth.Json/index.html#.Net-and-NetCore-support

Thank you for the PR I will take a look.

**Comment by kurt-mueller-osumc** [comment]
... not that it's a separate package 😬. I honestly thought I was just opening another namespace/module. 

Anyway, I've been using Thoth.Json for about 4 hours now and I really like it. Thank you for the great software and for all your hard work.

**Comment by MangelMaxime** [comment]
> ... not that it's a separate package grimacing.

For me it does, but perhaps there is place for improvement.

> In order to use Thoth.Json API on .Net or NetCore you need to use the Thoth.Json.Net package.

> Anyway, I've been using Thoth.Json for about 4 hours now and I really like it. Thank you for the great software and for all your hard work.

Thank you for the kind word and happy that you find it useful :)

**Comment by MangelMaxime** [comment]
I updated the documentation thank you for the PR
